
<div style="text-align: right; font-size: 8pt;">Updated on <?php echo date('m/d/Y'); ?></div>
<div style="display: inline-block; width: 100%;">
    <div style="float: left; width: 25%;"><div style="height: 180px;"><h2>By Amount</h2><?php echo $this->byamount; ?></div><img src="/uploads/Amountwholesalemtd.png"></div>
    <div style="float: left; width: 25%;"><div style="height: 180px;"><h2>By Units</h2><?php echo $this->bycount; ?></div><img src="/uploads/Countwholesalemtd.png"></div>
    <div style="float: left; width: 25%;"><div style="height: 180px;"><h2>By Product</h2><?php echo $this->bytype; ?></div><img src="/uploads/Typewholesalemtd.png"></div>
</div>