
<div style="text-align: right; font-size: 8pt;">Updated on <?php echo date('m/d/Y'); ?></div>
<div style="display: inline-block; width: 100%;">
    <div style="float: left; width: 25%;"><div style="height: 180px;"><h2>By Amount</h2><?php echo $this->byamount; ?></div><img src="/uploads/Amountmtd.png"></div>
    <div style="float: left; width: 25%;"><div style="height: 180px;"><h2>By Units</h2><?php echo $this->bycount; ?></div><img src="/uploads/Countmtd.png"></div>
    <div style="float: left; width: 25%;"><div style="height: 180px;"><h2>By Product</h2><?php echo $this->bytype; ?></div><img src="/uploads/Typemtd.png"></div>
    <div style="float: left; width: 25%;"><div style="height: 180px;"><h2>By Branch</h2><?php echo $this->bybranch; ?></div><img src="/uploads/Branchmtd.png"></div>
</div>