
<div style="text-align: right; font-size: 8pt;">Updated on <?php echo date('m/d/Y'); ?></div>
<div style="display: inline-block; width: 100%;">
    <div style="float: left; "><div style="width: 350px;"><h2>By Amount</h2><table width="100%"><?php echo $this->byamount; ?></table></div><br><img src="/uploads/10Amountmtd.png"></div>
    <div style="float: left; "><div style="width: 100px;">&nbsp;</div></div>
    <div style="float: left; "><div style="width: 350px;"><h2>By Units</h2><table width="100%"><?php echo $this->bycount; ?></table></div><br><img src="/uploads/10Countmtd.png"></div>
</div>