

<div style="display: inline-block; width: 100%;">
    <div style="float: left; "><div style="width: 350px;"><h2>By Amount</h2><table width="100%"><?php echo $this->byamount; ?></table></div><br><img src="/uploads/20Amountmtd.png"></div>
    <div style="float: left; "><div style="width: 100px;">&nbsp;</div></div>
    <div style="float: left; "><div style="width: 350px;"><h2>By Units</h2><table width="100%"><?php echo $this->bycount; ?></table></div><br><img src="/uploads/20Countmtd.png"></div>
</div>